services:
  php:
    image: sineverba/php8xc:latest
    volumes:
      - ./:/var/www
      - ~/.ssh:/root/.ssh:ro
      - ~/.composer:/root/.composer
    working_dir: /var/www
    environment:
      - PHP_CS_FIXER_IGNORE_ENV=true